language: csharp

mono: 5.2.0
dotnet: 2.0.0

install:
  - mozroots --import --sync
  # workaround for missing .net 4.5 targing pack
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 2.0.0
    - os: osx # OSX 10.12
      osx_image: xcode9.1
      dotnet: 2.0.0
      dist: trusty
      sudo: required

script: 
  - dotnet --info
  - dotnet restore
  - dotnet build -c Release
  - dotnet test tests/Freya.Core.Tests/Freya.Core.Tests.fsproj -c Release 
  - dotnet test tests/Freya.Core.Hopac.Tests/Freya.Core.Hopac.Tests.fsproj -c Release 
  - dotnet pack -c Release --include-symbols
  - dotnet tests/Freya.Core.Benchmarks/bin/Release/netcoreapp2.0/Freya.Core.Benchmarks.dll

branches:
  except:
    - gh-pages
